spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flowable-spring-boot?setUnicode=true&characterEncoding=utf8
    username: root
    password: 123
flowable:
  #关闭定时任务JOB
  async-executor-activate: false